{% set name = "spdx-license-matcher" %}
{% set version = "2.9" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/spdx/spdx-license-matcher/archive/v{{ version }}.tar.gz
  sha256: 176b4302cd1995b9b350601d6929ab9f02ef69172e7f418ff24f59895e767b39

build:
  entry_points:
    - spdx-license-matcher = spdx_license_matcher.matcher:matcher
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3
    - setuptools >=39.0.1
  run:
    - redis-py >=4.4.4,<4.6
    - requests =2.25
    - jpype1 >=1.7.0
    - jellyfish ==0.6.1
    - click ==7.0
    - python-dotenv >=0.17.1
    - wheel >=0.45.1
    - python >=3

test:
  imports:
    - spdx_license_matcher
  commands:
    - pip check
    - spdx-license-matcher --help
  requires:
    - pip

about:
  home: https://github.com/spdx/spdx-license-matcher
  summary: A tool to match license text with SPDX license list using a an algorithm with finds close matches.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
