{% set name = "spdx-license-matcher" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spdx/spdx-license-matcher/archive/v{{ version }}.tar.gz
  sha256: f8244615b823f828ac9a360e88d66cdea3ce46fd3296f0798fad0db8cd61d200

build:
  entry_points:
    - spdx-license-matcher = spdx_license_matcher.matcher:matcher
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3
    - setuptools >=39.0.1
  run:
    - click ==7.0
    - jellyfish ==0.6.1
    - jpype1 >=1.3.0
    - python >=3
    - python-dotenv >=0.17.1
    - redis-py ==3.2.1
    - requests >=2.25

test:
  imports:
    - spdx_license_matcher
  commands:
    - pip check
    - spdx-license-matcher --help
  requires:
    - pip

about:
  home: https://github.com/spdx/spdx-license-matcher
  summary: A tool to match license text with SPDX license list using a an algorithm with finds close matches.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
